local:
  service: S3
  access_key_id: ""
  secret_access_key: ""
  bucket: "aws-codestar-us-west-2-405549847598-csc517-ror-pipe"
  region: "us-west-2"   # e.g. 'us-east-1'
#  service: Disk
#  root: <%= Rails.root.join("storage") %>
 
test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>
 
amazon:
  service: S3
  access_key_id: ""
  secret_access_key: ""
  bucket: ""
  region: ""   # e.g. 'us-east-1'